package com.wangxinenpu.springbootdemo.dao.mapper.selfmachine;

import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoftRegionRef;
import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoftRegionRefExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OptSelfServiceMachinesSoftRegionRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int countByExample(OptSelfServiceMachinesSoftRegionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int deleteByExample(OptSelfServiceMachinesSoftRegionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int insert(OptSelfServiceMachinesSoftRegionRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int insertSelective(OptSelfServiceMachinesSoftRegionRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    List<OptSelfServiceMachinesSoftRegionRef> selectByExample(OptSelfServiceMachinesSoftRegionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    OptSelfServiceMachinesSoftRegionRef selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OptSelfServiceMachinesSoftRegionRef record, @Param("example") OptSelfServiceMachinesSoftRegionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OptSelfServiceMachinesSoftRegionRef record, @Param("example") OptSelfServiceMachinesSoftRegionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OptSelfServiceMachinesSoftRegionRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_region_ref
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OptSelfServiceMachinesSoftRegionRef record);
}