package com.wangxinenpu.springbootdemo.dao.mapper.selfmachine;

import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoftOrgRef;
import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoftOrgRefExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OptSelfServiceMachinesSoftOrgRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int countByExample(OptSelfServiceMachinesSoftOrgRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int deleteByExample(OptSelfServiceMachinesSoftOrgRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int insert(OptSelfServiceMachinesSoftOrgRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int insertSelective(OptSelfServiceMachinesSoftOrgRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    List<OptSelfServiceMachinesSoftOrgRef> selectByExample(OptSelfServiceMachinesSoftOrgRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    OptSelfServiceMachinesSoftOrgRef selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OptSelfServiceMachinesSoftOrgRef record, @Param("example") OptSelfServiceMachinesSoftOrgRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OptSelfServiceMachinesSoftOrgRef record, @Param("example") OptSelfServiceMachinesSoftOrgRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OptSelfServiceMachinesSoftOrgRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_org_ref
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OptSelfServiceMachinesSoftOrgRef record);
}