package com.wangxinenpu.springbootdemo.dao.mapper.selfmachine;


import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoft;
import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoftExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.HashMap;
import java.util.List;

public interface OptSelfServiceMachinesSoftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int countByExample(OptSelfServiceMachinesSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int deleteByExample(OptSelfServiceMachinesSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int insert(OptSelfServiceMachinesSoft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int insertSelective(OptSelfServiceMachinesSoft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    List<OptSelfServiceMachinesSoft> selectByExampleWithBLOBs(OptSelfServiceMachinesSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    List<OptSelfServiceMachinesSoft> selectByExample(OptSelfServiceMachinesSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    OptSelfServiceMachinesSoft selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OptSelfServiceMachinesSoft record, @Param("example") OptSelfServiceMachinesSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OptSelfServiceMachinesSoft record, @Param("example") OptSelfServiceMachinesSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OptSelfServiceMachinesSoft record, @Param("example") OptSelfServiceMachinesSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OptSelfServiceMachinesSoft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OptSelfServiceMachinesSoft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OptSelfServiceMachinesSoft record);

    /**
     * 搜索系统用户表列表，带分页
     *
     * @haoxz11MyBatis
     */
    List<OptSelfServiceMachinesSoft> getListByWhere(HashMap<String, Object> searchMap, RowBounds rowBounds);


    /**
     * 搜索系统用户表列表
     *
     */
    List<OptSelfServiceMachinesSoft> getListByWhere(HashMap<String, Object> searchMap);

    /**
     * 得到搜索系统用户表的记录数量
     *
     */
    int getCountByWhere(HashMap<String, Object> searchMap);
}