package com.wangxinenpu.springbootdemo.dao.mapper.selfmachine;

import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoftModelRef;
import com.wangxinenpu.springbootdemo.dataobject.po.OptSelfServiceMachinesSoftModelRefExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OptSelfServiceMachinesSoftModelRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int countByExample(OptSelfServiceMachinesSoftModelRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int deleteByExample(OptSelfServiceMachinesSoftModelRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int insert(OptSelfServiceMachinesSoftModelRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int insertSelective(OptSelfServiceMachinesSoftModelRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    List<OptSelfServiceMachinesSoftModelRef> selectByExample(OptSelfServiceMachinesSoftModelRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    OptSelfServiceMachinesSoftModelRef selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OptSelfServiceMachinesSoftModelRef record, @Param("example") OptSelfServiceMachinesSoftModelRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OptSelfServiceMachinesSoftModelRef record, @Param("example") OptSelfServiceMachinesSoftModelRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OptSelfServiceMachinesSoftModelRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_self_service_machines_soft_model_ref
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OptSelfServiceMachinesSoftModelRef record);
}