package com.wangxinenpu.springbootdemo.dao.mapper;

import com.wangxinenpu.springbootdemo.dataobject.po.SysCheckChangelog;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
import java.util.Map;


public interface SysCheckChangelogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_check_changelog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_check_changelog
     *
     * @mbggenerated
     */
    int insert(SysCheckChangelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_check_changelog
     *
     * @mbggenerated
     */
    int insertSelective(SysCheckChangelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_check_changelog
     *
     * @mbggenerated
     */
    SysCheckChangelog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_check_changelog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysCheckChangelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_check_changelog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysCheckChangelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_check_changelog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysCheckChangelog record);
    
    /**
     * 查询列表
     * @param map
     * @return
     */
    List<SysCheckChangelog> getSysCheckChangelogList(Map<String, Object> map, RowBounds rowBounds);
}