package com.wangxinenpu.springbootdemo.dataobject.po;

import star.vo.BaseVo;

import java.util.Date;

public class OptResourceCluster extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.server_id
     *
     * @mbggenerated
     */
    private Long serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.cluster_code
     *
     * @mbggenerated
     */
    private String clusterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.cluster_name
     *
     * @mbggenerated
     */
    private String clusterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.poit_num
     *
     * @mbggenerated
     */
    private Short poitNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.environment
     *
     * @mbggenerated
     */
    private Short environment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.service_id
     *
     * @mbggenerated
     */
    private Long serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.remark
     *
     * @mbggenerated
     */
    private String remark;

    private Short isValid;

    public Short getIsValid() {
        return isValid;
    }

    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    private Long managerId;

    private String managerName;

    public Long getManagerId() {
        return managerId;
    }

    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    public String getManagerName() {
        return managerName;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_resource_cluster.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.id
     *
     * @return the value of opt_resource_cluster.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.id
     *
     * @param id the value for opt_resource_cluster.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.server_id
     *
     * @return the value of opt_resource_cluster.server_id
     *
     * @mbggenerated
     */
    public Long getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.server_id
     *
     * @param serverId the value for opt_resource_cluster.server_id
     *
     * @mbggenerated
     */
    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.cluster_code
     *
     * @return the value of opt_resource_cluster.cluster_code
     *
     * @mbggenerated
     */
    public String getClusterCode() {
        return clusterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.cluster_code
     *
     * @param clusterCode the value for opt_resource_cluster.cluster_code
     *
     * @mbggenerated
     */
    public void setClusterCode(String clusterCode) {
        this.clusterCode = clusterCode == null ? null : clusterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.cluster_name
     *
     * @return the value of opt_resource_cluster.cluster_name
     *
     * @mbggenerated
     */
    public String getClusterName() {
        return clusterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.cluster_name
     *
     * @param clusterName the value for opt_resource_cluster.cluster_name
     *
     * @mbggenerated
     */
    public void setClusterName(String clusterName) {
        this.clusterName = clusterName == null ? null : clusterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.poit_num
     *
     * @return the value of opt_resource_cluster.poit_num
     *
     * @mbggenerated
     */
    public Short getPoitNum() {
        return poitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.poit_num
     *
     * @param poitNum the value for opt_resource_cluster.poit_num
     *
     * @mbggenerated
     */
    public void setPoitNum(Short poitNum) {
        this.poitNum = poitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.environment
     *
     * @return the value of opt_resource_cluster.environment
     *
     * @mbggenerated
     */
    public Short getEnvironment() {
        return environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.environment
     *
     * @param environment the value for opt_resource_cluster.environment
     *
     * @mbggenerated
     */
    public void setEnvironment(Short environment) {
        this.environment = environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.service_id
     *
     * @return the value of opt_resource_cluster.service_id
     *
     * @mbggenerated
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.service_id
     *
     * @param serviceId the value for opt_resource_cluster.service_id
     *
     * @mbggenerated
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.type
     *
     * @return the value of opt_resource_cluster.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.type
     *
     * @param type the value for opt_resource_cluster.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.remark
     *
     * @return the value of opt_resource_cluster.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.remark
     *
     * @param remark the value for opt_resource_cluster.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.create_time
     *
     * @return the value of opt_resource_cluster.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.create_time
     *
     * @param createTime the value for opt_resource_cluster.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_resource_cluster.modify_time
     *
     * @return the value of opt_resource_cluster.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_resource_cluster.modify_time
     *
     * @param modifyTime the value for opt_resource_cluster.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}