package com.wangxinenpu.springbootdemo.dataobject.po;

import star.vo.BaseVo;

import java.util.Date;

public class OptSelfServiceMachinesSoft extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.soft_name
     *
     * @mbggenerated
     */
    private String softName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.start_update_time
     *
     * @mbggenerated
     */
    private Date startUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.environment
     *
     * @mbggenerated
     */
    private Short environment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.soft_version
     *
     * @mbggenerated
     */
    private String softVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.version_remark
     *
     * @mbggenerated
     */
    private String versionRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.addr
     *
     * @mbggenerated
     */
    private String addr;
    private String pathKey;

    public String getPathKey() {
        return pathKey;
    }

    public void setPathKey(String pathKey) {
        this.pathKey = pathKey;
    }

    private String path;


    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.port
     *
     * @mbggenerated
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.passwd
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.update_strategy
     *
     * @mbggenerated
     */
    private Short updateStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.is_valid
     *
     * @mbggenerated
     */
    private Short isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.manager_id
     *
     * @mbggenerated
     */
    private Long managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.manager_name
     *
     * @mbggenerated
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.id
     *
     * @return the value of opt_self_service_machines_soft.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.id
     *
     * @param id the value for opt_self_service_machines_soft.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.soft_name
     *
     * @return the value of opt_self_service_machines_soft.soft_name
     *
     * @mbggenerated
     */
    public String getSoftName() {
        return softName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.soft_name
     *
     * @param softName the value for opt_self_service_machines_soft.soft_name
     *
     * @mbggenerated
     */
    public void setSoftName(String softName) {
        this.softName = softName == null ? null : softName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.source
     *
     * @return the value of opt_self_service_machines_soft.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.source
     *
     * @param source the value for opt_self_service_machines_soft.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.start_update_time
     *
     * @return the value of opt_self_service_machines_soft.start_update_time
     *
     * @mbggenerated
     */
    public Date getStartUpdateTime() {
        return startUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.start_update_time
     *
     * @param startUpdateTime the value for opt_self_service_machines_soft.start_update_time
     *
     * @mbggenerated
     */
    public void setStartUpdateTime(Date startUpdateTime) {
        this.startUpdateTime = startUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.update_time
     *
     * @return the value of opt_self_service_machines_soft.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.update_time
     *
     * @param updateTime the value for opt_self_service_machines_soft.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.environment
     *
     * @return the value of opt_self_service_machines_soft.environment
     *
     * @mbggenerated
     */
    public Short getEnvironment() {
        return environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.environment
     *
     * @param environment the value for opt_self_service_machines_soft.environment
     *
     * @mbggenerated
     */
    public void setEnvironment(Short environment) {
        this.environment = environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.soft_version
     *
     * @return the value of opt_self_service_machines_soft.soft_version
     *
     * @mbggenerated
     */
    public String getSoftVersion() {
        return softVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.soft_version
     *
     * @param softVersion the value for opt_self_service_machines_soft.soft_version
     *
     * @mbggenerated
     */
    public void setSoftVersion(String softVersion) {
        this.softVersion = softVersion == null ? null : softVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.version_remark
     *
     * @return the value of opt_self_service_machines_soft.version_remark
     *
     * @mbggenerated
     */
    public String getVersionRemark() {
        return versionRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.version_remark
     *
     * @param versionRemark the value for opt_self_service_machines_soft.version_remark
     *
     * @mbggenerated
     */
    public void setVersionRemark(String versionRemark) {
        this.versionRemark = versionRemark == null ? null : versionRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.addr
     *
     * @return the value of opt_self_service_machines_soft.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.addr
     *
     * @param addr the value for opt_self_service_machines_soft.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.port
     *
     * @return the value of opt_self_service_machines_soft.port
     *
     * @mbggenerated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.port
     *
     * @param port the value for opt_self_service_machines_soft.port
     *
     * @mbggenerated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.account
     *
     * @return the value of opt_self_service_machines_soft.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.account
     *
     * @param account the value for opt_self_service_machines_soft.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.passwd
     *
     * @return the value of opt_self_service_machines_soft.passwd
     *
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.passwd
     *
     * @param passwd the value for opt_self_service_machines_soft.passwd
     *
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.update_strategy
     *
     * @return the value of opt_self_service_machines_soft.update_strategy
     *
     * @mbggenerated
     */
    public Short getUpdateStrategy() {
        return updateStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.update_strategy
     *
     * @param updateStrategy the value for opt_self_service_machines_soft.update_strategy
     *
     * @mbggenerated
     */
    public void setUpdateStrategy(Short updateStrategy) {
        this.updateStrategy = updateStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.is_valid
     *
     * @return the value of opt_self_service_machines_soft.is_valid
     *
     * @mbggenerated
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.is_valid
     *
     * @param isValid the value for opt_self_service_machines_soft.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.manager_id
     *
     * @return the value of opt_self_service_machines_soft.manager_id
     *
     * @mbggenerated
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.manager_id
     *
     * @param managerId the value for opt_self_service_machines_soft.manager_id
     *
     * @mbggenerated
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.manager_name
     *
     * @return the value of opt_self_service_machines_soft.manager_name
     *
     * @mbggenerated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.manager_name
     *
     * @param managerName the value for opt_self_service_machines_soft.manager_name
     *
     * @mbggenerated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.create_time
     *
     * @return the value of opt_self_service_machines_soft.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.create_time
     *
     * @param createTime the value for opt_self_service_machines_soft.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.modify_time
     *
     * @return the value of opt_self_service_machines_soft.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.modify_time
     *
     * @param modifyTime the value for opt_self_service_machines_soft.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft.remark
     *
     * @return the value of opt_self_service_machines_soft.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft.remark
     *
     * @param remark the value for opt_self_service_machines_soft.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}