package com.wangxinenpu.springbootdemo.dataobject.po;

import star.vo.BaseVo;

import java.util.Date;

public class OptSelfServiceMachinesSoftRegionRef extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft_region_ref.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft_region_ref.self_service_id
     *
     * @mbggenerated
     */
    private Long selfServiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft_region_ref.region_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft_region_ref.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_self_service_machines_soft_region_ref.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft_region_ref.id
     *
     * @return the value of opt_self_service_machines_soft_region_ref.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft_region_ref.id
     *
     * @param id the value for opt_self_service_machines_soft_region_ref.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft_region_ref.self_service_id
     *
     * @return the value of opt_self_service_machines_soft_region_ref.self_service_id
     *
     * @mbggenerated
     */
    public Long getSelfServiceId() {
        return selfServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft_region_ref.self_service_id
     *
     * @param selfServiceId the value for opt_self_service_machines_soft_region_ref.self_service_id
     *
     * @mbggenerated
     */
    public void setSelfServiceId(Long selfServiceId) {
        this.selfServiceId = selfServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft_region_ref.region_id
     *
     * @return the value of opt_self_service_machines_soft_region_ref.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft_region_ref.region_id
     *
     * @param regionId the value for opt_self_service_machines_soft_region_ref.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft_region_ref.create_time
     *
     * @return the value of opt_self_service_machines_soft_region_ref.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft_region_ref.create_time
     *
     * @param createTime the value for opt_self_service_machines_soft_region_ref.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_self_service_machines_soft_region_ref.modify_time
     *
     * @return the value of opt_self_service_machines_soft_region_ref.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_self_service_machines_soft_region_ref.modify_time
     *
     * @param modifyTime the value for opt_self_service_machines_soft_region_ref.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}