package com.wangxinenpu.springbootdemo.dataobject.po;

import star.vo.BaseVo;

import java.util.Date;

public class SysCheckChangelog extends BaseVo{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.config_id
     *
     * @mbggenerated
     */
    private Long configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.log_id
     *
     * @mbggenerated
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.type_before
     *
     * @mbggenerated
     */
    private String typeBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.type_after
     *
     * @mbggenerated
     */
    private String typeAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.floor_before
     *
     * @mbggenerated
     */
    private String floorBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.floor_after
     *
     * @mbggenerated
     */
    private String floorAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_check_changelog.remark
     *
     * @mbggenerated
     */
    private String remark;
    
    /**
     * 操作人姓名
     */
    private String operatorName;
    
    /**
     * IP
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.id
     *
     * @return the value of sys_check_changelog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.id
     *
     * @param id the value for sys_check_changelog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.config_id
     *
     * @return the value of sys_check_changelog.config_id
     *
     * @mbggenerated
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.config_id
     *
     * @param configId the value for sys_check_changelog.config_id
     *
     * @mbggenerated
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.log_id
     *
     * @return the value of sys_check_changelog.log_id
     *
     * @mbggenerated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.log_id
     *
     * @param logId the value for sys_check_changelog.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.type_before
     *
     * @return the value of sys_check_changelog.type_before
     *
     * @mbggenerated
     */
    public String getTypeBefore() {
        return typeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.type_before
     *
     * @param typeBefore the value for sys_check_changelog.type_before
     *
     * @mbggenerated
     */
    public void setTypeBefore(String typeBefore) {
        this.typeBefore = typeBefore == null ? null : typeBefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.type_after
     *
     * @return the value of sys_check_changelog.type_after
     *
     * @mbggenerated
     */
    public String getTypeAfter() {
        return typeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.type_after
     *
     * @param typeAfter the value for sys_check_changelog.type_after
     *
     * @mbggenerated
     */
    public void setTypeAfter(String typeAfter) {
        this.typeAfter = typeAfter == null ? null : typeAfter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.floor_before
     *
     * @return the value of sys_check_changelog.floor_before
     *
     * @mbggenerated
     */
    public String getFloorBefore() {
        return floorBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.floor_before
     *
     * @param floorBefore the value for sys_check_changelog.floor_before
     *
     * @mbggenerated
     */
    public void setFloorBefore(String floorBefore) {
        this.floorBefore = floorBefore == null ? null : floorBefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.floor_after
     *
     * @return the value of sys_check_changelog.floor_after
     *
     * @mbggenerated
     */
    public String getFloorAfter() {
        return floorAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.floor_after
     *
     * @param floorAfter the value for sys_check_changelog.floor_after
     *
     * @mbggenerated
     */
    public void setFloorAfter(String floorAfter) {
        this.floorAfter = floorAfter == null ? null : floorAfter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.create_time
     *
     * @return the value of sys_check_changelog.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.create_time
     *
     * @param createTime the value for sys_check_changelog.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.modify_time
     *
     * @return the value of sys_check_changelog.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.modify_time
     *
     * @param modifyTime the value for sys_check_changelog.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_check_changelog.remark
     *
     * @return the value of sys_check_changelog.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_check_changelog.remark
     *
     * @param remark the value for sys_check_changelog.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
    
    
}